test

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -31,7 +31,7 @@ jobs:
       run: terraform apply -auto-approve -var="public_key_string=$PUBLIC_KEY"
 
     - name: Print Terraform Outputs
-      run: $TERRAFORM_CLI_PATH output
+      run: $TERRAFORM_CLI_PATH/terraform output
 
     # Setup private SSH key to access the EC2 instance
     - name: Setup SSH Private Key
@@ -39,18 +39,18 @@ jobs:
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_rsa
         chmod 400 /tmp/id_rsa
 
-#    # SSH into EC2 instance and test the Nginx deployment
-#    - name: Test Nginx Deployment
-#      run: |
-#        EC2_IP=$($TERRAFORM_CLI_PATH output ec2_public_ip)
-#        ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ec2-user@$EC2_IP "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080" > response_code.txt
-#        RESPONSE_CODE=$(cat response_code.txt)
-#        if [ "$RESPONSE_CODE" == "200" ]; then
-#          echo "Nginx deployment successful!"
-#        else
-#          echo "Nginx deployment failed!"
-#          exit 1
-#        fi
+    # SSH into EC2 instance and test the Nginx deployment
+    - name: Test Nginx Deployment
+      run: |
+        EC2_IP=$($TERRAFORM_CLI_PATH/terraform output ec2_public_ip)
+        ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ec2-user@$EC2_IP "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080" > response_code.txt
+        RESPONSE_CODE=$(cat response_code.txt)
+        if [ "$RESPONSE_CODE" == "200" ]; then
+          echo "Nginx deployment successful!"
+        else
+          echo "Nginx deployment failed!"
+          exit 1
+        fi
 
     # Destroy the infrastructure
     - name: Terraform Destroy
